import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/WrapperComponents/Navbar";
import Footer from "@/components/WrapperComponents/Footer";
import SmoothScroll from "@/components/WrapperComponents/SmoothScroll";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${inter.className} antialiased`} suppressHydrationWarning>
        <SmoothScroll>
          <Navbar/>
          {children}
          <Footer/>
        </SmoothScroll>
      </body>
    </html>
  );
}
